import { describe, it, expect } from 'vitest';
import vectors from './fixtures/scoreline_vectors.json';
import { topScorelines } from '../lib/scorelines';
import { DC_RHO, SCORE_MATRIX_MAXG } from '../lib/constants';

// Parity with engine/dixon_coles.py score_matrix — vectors generated by
// web/tests/fixtures/gen_scorelines.py from the actual engine (same culture as
// golden_vectors.json for value.ts). Regenerate when engine RHO/MAXG change.

describe('scorelines parity (engine golden vectors)', () => {
  it('mirrored constants match the engine values the vectors were built with', () => {
    expect(DC_RHO).toBe(vectors.rho);
    expect(SCORE_MATRIX_MAXG).toBe(vectors.maxg);
  });

  for (const c of vectors.cases) {
    it(`top-5 scorelines match engine for λ=(${c.lambda_home}, ${c.lambda_away})`, () => {
      const top = topScorelines(c.lambda_home, c.lambda_away, 5);
      expect(top).toHaveLength(5);
      top.forEach((s, i) => {
        expect(`${s.home}-${s.away}`).toBe(`${c.top[i].home}-${c.top[i].away}`);
        expect(s.p).toBeCloseTo(c.top[i].p, 12);
      });
    });
  }
});

describe('topScorelines sanity', () => {
  it('probabilities are descending and the full matrix sums to 1', () => {
    const all = topScorelines(1.31, 1.1, (SCORE_MATRIX_MAXG + 1) ** 2);
    for (let i = 1; i < all.length; i++) expect(all[i].p).toBeLessThanOrEqual(all[i - 1].p);
    const sum = all.reduce((acc, s) => acc + s.p, 0);
    expect(sum).toBeCloseTo(1, 12);
  });

  it('a strong favourite tops with a winning scoreline', () => {
    const [best] = topScorelines(2.05, 0.7, 1);
    expect(best.home).toBeGreaterThan(best.away);
  });

  it('defaults to top-2 (the card hint)', () => {
    expect(topScorelines(1.2, 1.2)).toHaveLength(2);
  });
});
