import { describe, it, expect } from 'vitest';
import golden from './fixtures/golden_vectors.json';
import {
  toDecimal,
  ev,
  kellyFraction,
  isQuarterLine,
  isHalfLine,
  evWithPush,
  kellyWithPush,
  quarterComponents,
  evaluate,
  evaluateModelTotals,
  evaluateModelTotalsQuarter,
  type EvaluateOptions,
} from '../lib/value';

// TU5 / TU7 / TU8: lib/value.ts must reproduce engine/value.py exactly on the golden vectors
// (web/tests/fixtures/golden_vectors.json, generated by gen_golden.py).

describe('toDecimal parity (TU7)', () => {
  for (const c of golden.to_decimal) {
    it(`${c.fmt} ${c.value} -> ${c.expected}`, () => {
      expect(toDecimal(c.value, c.fmt)).toBeCloseTo(c.expected, 12);
    });
  }

  it('rejects decimal <= 1 (TU7)', () => {
    expect(() => toDecimal(1.0, 'decimal')).toThrow();
    expect(() => toDecimal(-50, 'american')).not.toThrow(); // -50 -> 3.0 valid
  });

  it('rejects unknown format', () => {
    expect(() => toDecimal(2, 'klingon')).toThrow();
  });
});

describe('ev parity (TU5)', () => {
  for (const c of golden.ev) {
    it(`p=${c.p} d=${c.d}`, () => {
      expect(ev(c.p, c.d)).toBeCloseTo(c.expected, 12);
    });
  }
});

describe('kellyFraction parity (TU5)', () => {
  for (const c of golden.kelly) {
    it(`p=${c.p} d=${c.d} f=${c.fraction}`, () => {
      expect(kellyFraction(c.p, c.d, c.fraction)).toBeCloseTo(c.expected, 12);
    });
  }
});

describe('isQuarterLine parity (TU8)', () => {
  for (const c of golden.is_quarter_line) {
    it(`point=${c.point}`, () => {
      expect(isQuarterLine(c.point)).toBe(c.expected);
    });
  }
});

describe('isHalfLine parity (TB7)', () => {
  for (const c of golden.is_half_line) {
    it(`point=${c.point}`, () => {
      expect(isHalfLine(c.point)).toBe(c.expected);
    });
  }
});

describe('push-aware model-mode arithmetic parity (TB6)', () => {
  for (const c of golden.ev_with_push) {
    it(`evWithPush pWin=${c.pWin} pPush=${c.pPush} d=${c.d}`, () => {
      expect(evWithPush(c.pWin, c.pPush, c.d)).toBeCloseTo(c.expected, 12);
    });
  }
  for (const c of golden.kelly_with_push) {
    it(`kellyWithPush pWin=${c.pWin} pPush=${c.pPush} d=${c.d}`, () => {
      expect(kellyWithPush(c.pWin, c.pPush, c.d, c.fraction)).toBeCloseTo(c.expected, 12);
    });
  }
  golden.evaluate_model_totals.forEach((c, i) => {
    it(`evaluateModelTotals case ${i}`, () => {
      const r = evaluateModelTotals(c.pWin, c.pPush, c.userValue, c.userFormat);
      const e = c.expected;
      expect(r.decimal_odds).toBeCloseTo(e.decimal_odds, 12);
      expect(r.ev).toBeCloseTo(e.ev, 12);
      expect(r.value).toBe(e.value);
      expect(r.kelly_fraction).toBeCloseTo(e.kelly_fraction, 12);
      expect(r.kelly_approximate).toBe(false);
    });
  });
  golden.evaluate_model_totals_quarter.forEach((c, i) => {
    it(`evaluateModelTotalsQuarter case ${i}`, () => {
      const r = evaluateModelTotalsQuarter(
        c.lo as [number, number],
        c.hi as [number, number],
        c.userValue,
        c.userFormat,
      );
      const e = c.expected;
      expect(r.ev).toBeCloseTo(e.ev, 12);
      expect(r.kelly_fraction).toBeCloseTo(e.kelly_fraction, 12);
      expect(r.kelly_approximate).toBe(true);   // quarter Kelly is approximate (TB7)
    });
  });
  it('quarterComponents splits to neighbours', () => {
    expect(quarterComponents(2.25)).toEqual([2.0, 2.5]);
    expect(quarterComponents(3.75)).toEqual([3.5, 4.0]);
    expect(() => quarterComponents(2.5)).toThrow();
  });
});

describe('evaluate parity (TU5 / TU8)', () => {
  golden.evaluate.forEach((c, i) => {
    it(`case ${i} (${c.userFormat})`, () => {
      const r = evaluate(c.p, c.userValue, c.userFormat, c.opts as EvaluateOptions);
      const e = c.expected as Record<string, unknown>;
      expect(r.decimal_odds).toBeCloseTo(e.decimal_odds as number, 12);
      expect(r.implied_prob).toBeCloseTo(e.implied_prob as number, 12);
      expect(r.p_pinnacle_novig).toBeCloseTo(e.p_pinnacle_novig as number, 12);
      expect(r.line_mismatch).toBe(e.line_mismatch);
      if (e.ev === null) expect(r.ev).toBeNull();
      else expect(r.ev as number).toBeCloseTo(e.ev as number, 12);
      expect(r.value).toBe(e.value);
      if (e.kelly_fraction === null) expect(r.kelly_fraction).toBeNull();
      else expect(r.kelly_fraction as number).toBeCloseTo(e.kelly_fraction as number, 12);
      if ('approximate' in e) expect(Boolean(r.approximate)).toBe(e.approximate);
    });
  });
});
